trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: 'Build'
    jobs:
      - job: 'Build'
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: 'build'
              Dockerfile: './Dockerfile'
              arguments: '--target build'
      - job: 'Test'
        steps:
          - task: PowerShell@2
            inputs:
              targetType: inline
              script: |
                docker build --target test -t TodoList:$env:BUILDID .
                docker create -ti --name testcontainer TodoList:$env:BUILDID
                docker cp testcontainer:/src/TodoList.Tests/TestResults/ $env:ARTIFACTDIR/testresults
                ls $env:ARTIFACTDIR/testresults
                echo $env:ARTIFACTDIR/testresults
                docker rm -fv testcontainer
            env:
              BUILDID: $(Build.BuildId)
              ARTIFACTDIR: $(Build.ArtifactStagingDirectory)
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'VSTest'
              testResultsFiles: '**/*.trx'
              searchFolder: '$(Build.ArtifactStagingDirectory)/testresults'
              failTaskOnFailedTests: true

  - stage: 'Deploy_DEV'
    dependsOn: Build
    jobs:
      - job: 'Deploy'
        dependsOn: Approve
        steps:
          - task: CmdLine@2
            inputs:
              script: echo deployed successfully